### ISSUE TITLE
Shown text for menu items

### ISSUE THREAD

**Issue by ghost** [sweetsurrenderdk/sweetsurrenderdk.github.io#14]
Having entered a menu item in English and needing to translate to Danish. It is not possible  to see what the menu item is about anywhere but under "Advanced". The English text should somehow be displayed under "Basic" view. See video demonstrating  it here: http://screencast.com/t/4vjUMIZS8

**Comment by mrzapp** [comment]
I will try to think of a fallback logic for the item names
