### ISSUE TITLE
Attaching one menu item to multiple categories

### ISSUE THREAD

**Issue by ghost** [sweetsurrenderdk/sweetsurrenderdk.github.io#19]
Many of our menu items belongs to more than one category.  Example: "Homemade grilled sandwiches" belongs to three categories: "Breakfast", "Children's Menu" and "Snacks". It would therefore be great if each menu item could be attached to more that one category OR that menu items can be greated multiple times, but then sorted by category in the  right pane.

**Comment by mrzapp** [comment]
Solved by using tags instead. You can now add your own custom tags to any menu item and they will show up in the pane on the left.
